
#BASIC ENEMY SETTINGS
ENEMY_GOLD_DROP = 20
ENEMY_HEALTH = 100
ENEMY_SPEED = 1.5
ENEMY_DAMAGE = 50


#BASIC TOWER SETTINGS
TOWER_COST = 100
TOWER_RANGE = 150
TOWER_DAMAGE = 20
TOWER_FIRE_RATE = 2.0
BULLET_SPEED = 5.0
BULLET_DESPAWN_TIME = 5

# PIERCING TOWER SETTINGS
PIERCING_TOWER_COST = 700
PIERCING_TOWER_RANGE = 150
PIERCING_TOWER_DAMAGE = 50
PIERCING_TOWER_FIRE_RATE = 0.4
PIERCING_BULLET_SPEED = 14.0
PIERCING_BULLET_DESPAWN_TIME = 0.15

#SNIPER TOWER SETTINGS
SNIPER_TOWER_COST = 200
SNIPER_TOWER_RANGE = 300
SNIPER_TOWER_DAMAGE = 80
SNIPER_TOWER_FIRE_RATE = 1.2
SNIPER_TOWER_BULLET_SPEED = 10.0
SNIPER_TOWER_RANGE = 250


#BOMBER TOWER SETTINGS
BOMBER_TOWER_COST = 800
BOMBER_TOWER_RANGE = 180
BOMBER_EXPLOSION_DAMAGE = 80
BOMBER_EXPLOSION_RADIUS = 90
BOMBER_TOWER_FIRE_RATE = 0.3
BOMBER_BULLET_SPEED = 12.0


#BETTER SNIPER TOWER SETTINGS
BETTER_SNIPER_TOWER_COST = 550
BETTER_SNIPER_TOWER_RANGE = 350
BETTER_SNIPER_TOWER_DAMAGE = 160
BETTER_SNIPER_TOWER_FIRE_RATE = 1.5
BETTER_SNIPER_TURRET_BULLET_SPEED = 20.0


# FREEZE TOWER SETTINGS
FREEZE_TOWER_COST = 400
FREEZE_TOWER_RANGE = 110        
FREEZE_DURATION = 1.0         
FREEZE_FIRE_RATE = 0.3
FREEZE_MIN_ENEMIES_IN_RANGE = 1

#TWIN TOWER SETTINGS
TWIN_TOWER_COST = 300
TWIN_TOWER_RANGE = 150
TWIN_TOWER_DAMAGE = 25
TWIN_TOWER_FIRE_RATE = 3.5

#BETTER TWIN TOWER SETTINGS
BETTER_TWIN_TOWER_COST = 600
BETTER_TWIN_TOWER_RANGE = 200
BETTER_TWIN_TOWER_DAMAGE = 12
BETTER_TWIN_TOWER_FIRE_RATE = 12



#GOLD
STARTING_GOLD = 250

#PLAYER
PLAYER_HP = 1000